### ISSUE TITLE
[FEATURE]: 수강 신청 > 수강 현황을 새로운 페이지로 만들어 메뉴로 이동

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#305]
**Description**
수강 신청을 하면서 수강 현황을 수정하려면 하단으로 스크롤을 내려야만 하는 불편함이 있다. 
![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/ea1c147b-0c6a-45c8-bbf3-6c473fcdc2c9)
수업 > 수강 신청 밑에 수강 현황 메뉴를 추가하여 별도의 페이지로 구성하는 것으로 수정 필요.

**Comment by smaker** [comment]
## TODO
- [x] "수강 현황" 메뉴 추가
- [x] "수강 현황" 페이지 분리
- [x] "수강 현황"과 "수강 신청" route 중첩 오류 수정
